---
- name: user <|> Set root password
  ansible.builtin.user:
    name: root
    password: "{{ os_admin_password_sha512 | default(root_password_os_admin_password_sha512) }}"
  no_log: true
  when: (os_admin_password_sha512 is defined and os_admin_password_sha512 is not none) or (root_password_os_admin_password_sha512 is defined and root_password_os_admin_password_sha512 is not none)
