---
- name: "hostname <|> Set {{ inventory_hostname }} hostname"
  ansible.builtin.hostname:
    name: "{{ set_hostname_fqdn | ternary( inventory_hostname + '.' + (set_hostname_domain_name | default(bb_domain_name, true) | default('cluster.local', true)), inventory_hostname ) }}"
  tags:
    - identify
