- name: package <|> Install grubby
  ansible.builtin.package:
    name: grubby
    state: present

- name: shell <|> Get current kernel parameters
  ansible.builtin.shell: "set -o pipefail && grubby --info=DEFAULT | grep args"
  args:
    executable: /bin/bash
  register: current_kernel_parameters
  changed_when: False

- name: command <|> Update os kernel parameters
  ansible.builtin.command: "grubby --args='{{ item }}' --update-kernel=DEFAULT"
  loop: "{{ os_kernel_parameters.split(' ') | default([]) }}"
  when:
    - os_kernel_parameters is defined and os_kernel_parameters is not none
    - item not in current_kernel_parameters.stdout

- name: command <|> Update hw kernel parameters
  ansible.builtin.command: "grubby --args='{{ item }}' --update-kernel=DEFAULT"
  loop: "{{ hw_kernel_parameters.split(' ') | default([]) }}"
  when:
    - hw_kernel_parameters is defined and hw_kernel_parameters is not none
    - item not in current_kernel_parameters.stdout

- name: sysctl <|> Update sysctl parameters
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: "{{ kernel_config_sysctl_reload | ternary('yes','no') }}"
  with_dict: "{{ os_sysctl }}"
  when: os_sysctl is defined
