---
- name: managements playbook
  hosts: "fn_management"
  roles:

    - role: bluebanquise.high_availability.pcs
      tags: pcs
    - role: bluebanquise.high_availability.drbd
      tags: drbd
    - role: bluebanquise.high_availability.haproxy
      tags: haproxy
    - role: bluebanquise.high_availability.keepalived
      tags: keepalived
 