---
- name: managements playbook
  hosts: "fn_management"
  roles:

    - role: bluebanquise.logging.rsyslog
      tags: rsyslog
      vars:
        rsyslog_profile: server
    - role: bluebanquise.logging.rsyslog
      tags: rsyslog
      vars:
        rsyslog_profile: client     
    - role: bluebanquise.logging.loki
      tags: loki
