---
- name: managements playbook
  hosts: "fn_management"
  roles:

    - role: bluebanquise.security.auditd
      tags: auditd
    - role: bluebanquise.security.google_authenticator
      tags: google_authenticator
      vars:
        google_authenticator_mfa_mode: publickey
    - role: bluebanquise.security.google_authenticator
      tags: google_authenticator
      vars:
        google_authenticator_mfa_mode: password