---

- name: package <|> Install sudo
  ansible.builtin.package:
    name: sudo
    state: present

- name: blockinfile <|> Add sudoers users and groups
  ansible.builtin.blockinfile:
    path: "{{ item.file_name | default('/etc/sudoers') }}"
    state: present
    create: true
    owner: root
    group: root
    mode: '0600'
    block: |
      {{ item.name }} {{ item.privilege }}
    validate: 'visudo -cf %s'
  loop: "{{ sudoers }}"
  when: sudoers is defined and sudoers
