---
# For more details, please refer to https://ubuntu.com/server/docs/security-apparmor
- name: "service <|> Manage apparmor state"
  ansible.builtin.service:
    name: apparmor
    enabled: "{% if (os_access_control | default(access_control_os_access_control)) == 'enforcing' %}yes{% else %}no{% endif %}"
    state: "{% if (os_access_control | default(access_control_os_access_control)) == 'enforcing' %}started{% else %}stopped{% endif %}"
  tags:
    - service
