- name: ufw <|> "Add http service to firewall"
  community.general.ufw:
    rule: allow
    name: Apache
  when:
    - os_firewall | default(false) | bool
  tags:
    - firewall

- name: ufw <|> "Add tftp service to firewall"
  community.general.ufw:
    rule: allow
    port: '69'
    proto: udp
  when:
    - os_firewall | default(false) | bool
  tags:
    - firewall
